# Generated by Django 5.2.1 on 2025-06-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('instruction', models.TextField(max_length=4000)),
                ('image_url', models.URLField()),
                ('type', models.CharField(choices=[('Custom', 'Custom'), ('Original', 'Original')], max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('max_players', models.PositiveIntegerField()),
                ('min_players', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardgames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
