# Generated by Django 5.2.2 on 2025-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_boardgame_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
