# Generated by Django 5.2.2 on 2025-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_alter_boardgame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
