# Generated by Django 5.2.2 on 2025-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_alter_boardgame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
