# Generated by Django 5.2.2 on 2025-06-06 10:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_alter_boardgame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='media/'),
        ),
    ]
