# Generated by Django 5.2.2 on 2025-06-11 09:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_alter_boardgame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.ImageField(blank=True, max_length=5000, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='media/'),
        ),
    ]
