# Generated by Django 5.2.2 on 2025-06-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0007_rename_image_url_boardgame_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgame',
            old_name='image',
            new_name='image_url',
        ),
    ]
