# Generated by Django 5.2.2 on 2025-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0008_rename_image_boardgame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
